### ISSUE TITLE
Getting error while packaging the deb file...

### ISSUE THREAD

**Issue by mdrs2** [itsnebulalol/permasigner#22]
Getting this Error in the last stage
##
[*] Packaging the deb file...
Traceback (most recent call last):
  File "/Users/dani/permasigner/main.py", line 412, in <module>
    main(args)
  File "/Users/dani/permasigner/main.py", line 395, in main
    subprocess.run(f"./dpkg-deb -Zxz --root-owner-group -b {tmpfolder}/deb output/{app_name.replace(' ', '')}.deb".split(), stdout=subprocess.DEVNULL)
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: './dpkg-deb'

## Version Information
- Mac Version: Monterey 12.4
- dpkg installed by Brew but showed me this message once installed: This installation of dpkg is not configured to install software, so commands such as `dpkg -i`, `dpkg --configure` will fail.

**Comment by itsnebulalol** [comment]
Hi there, i’ll be fixing this later.

**Comment by itsnebulalol** [comment]
This should be fixed, reopen if it isnt.
