### ISSUE TITLE
NameError: name 'copy' is not defined

### ISSUE THREAD

**Issue by IvanKulagin** [itsnebulalol/permasigner#23]
```
➜  permasigner git:(main) ✗ python main.py                 
IPA Permasigner | Version main-be24cef
Program created by Nebula | Original scripts created by zhuowei | CoreTrust bypass by Linus Henze

[*] dpkg-deb not found, downloading.
Traceback (most recent call last):
  File "/home/ivan/Documents/permasigner/main.py", line 403, in <module>
    main(args)
  File "/home/ivan/Documents/permasigner/main.py", line 126, in main
    DpkgDeb.download_linux_64(args)
  File "/home/ivan/Documents/permasigner/utils/downloader.py", line 29, in download_linux_64
    copy("usr/bin/dpkg-deb", "dpkg-deb")
NameError: name 'copy' is not defined
```

I'm using Arch Linux with Python 3.10.5

**Comment by itsnebulalol** [comment]
Run `git pull` and try again

**Comment by IvanKulagin** [comment]
Didn't help but I've created a pull request with fix that worked https://github.com/itsnebulalol/permasigner/pull/24

**Comment by itsnebulalol** [comment]
Fixed in pr
